trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: GitHubSecrets # This refers to the variable group containing GITHUB_TOKEN

steps:
- checkout: self
  clean: true

- script: |
    echo Authenticating to GitHub
    git config --global url.https://$(GITHUB_TOKEN)@github.com/.insteadOf https://github.com/
    echo Navigate to the Maven project folder
    cd CucumberJavaProjectWithSeleniumAndTestNG # Replace with the folder containing your pom.xml
    echo Run Maven Tests with full error stack trace
    mvn clean test -e
  displayName: "Run Maven Tests with -e switch"

# Publish Surefire reports as build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/CucumberJavaProjectWithSeleniumAndTestNG/target/surefire-reports'
    artifactName: 'surefire-reports'
    publishLocation: 'Container'
  displayName: "Publish Surefire Reports"