trigger:
- main  # Replace with your branch name if not `main`

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Use the Library Group to define your GitHub token securely
  - group: GitHubSecrets

steps:
# Step 1: Connect to the VPN
- script: |
    echo "Connecting to Sophos VPN..."
    sophosvpn connect --server "125.5.210.68" --user "pfeniza" --password "gj&cA7Hsek"
    echo "VPN connected successfully."
  displayName: "Connect to VPN"

# Step 2: Checkout the code
- checkout: self
  clean: true
  displayName: "Checkout Code"

# Step 3: Run Maven Tests
- script: |
    echo "Authenticating GitHub..."
    git config --global url.https://$(GITHUB_TOKEN)@github.com/.insteadOf https://github.com/

    echo "Navigating to Maven project folder..."
    cd CucumberJavaProjectWithSeleniumAndTestNG

    echo "Running Maven Tests..."
    mvn clean test -e
  displayName: "Run Maven Tests"

# Step 4: Publish Surefire Reports as Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/CucumberJavaProjectWithSeleniumAndTestNG/target/surefire-reports'
    artifactName: 'surefire-reports'
    publishLocation: 'Container'
  displayName: "Publish Surefire Reports"